# Generated by Django 3.1 on 2020-12-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_is_activate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='is_activate',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
