# Generated by Django 3.1 on 2020-12-29 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20201229_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='won_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
