# Generated by Django 3.1 on 2020-12-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20201230_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='highest_bid',
            field=models.ManyToManyField(blank=True, related_name='highest_bid', to='auctions.Bids'),
        ),
    ]
