# Generated by Django 3.1 on 2021-01-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_listing_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='categories',
        ),
        migrations.AddField(
            model_name='category',
            name='listings',
            field=models.ManyToManyField(blank=True, related_name='listings', to='auctions.Listing'),
        ),
    ]
